### ISSUE TITLE
[Bug] IOException (occurs when the user moves to another page after SSE subscription succeeds)

### ISSUE THREAD

**Issue by yeonleaf** [yeonleaf/plantodo#32]
## Describe the bug

어떤 페이지에서 subscribe 완료 후 메세지를 보내는 중에 다른 페이지로 이동하는 경우 IOException 발생
IOException 발생 이후 두 가지 경우의 수가 있다. 정확히 어떤 상황에서 두 가지가 갈리는지는 알 수 없다.

#### 1. IOException 발생 이후 ResponseBodyEmitter가 completed되는 경우 
(이 경우 서버에서 더 이상 할 수 있는 게 없음)
(하지만 브라우저에서는 자동으로 연결 시도를 하게 되며, re-connection이 가능하기도 함)
```
org.apache.catalina.connector.ClientAbortException: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:199)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:91)
	at demo.plantodo.controller.SseController$SendAlarmRunnable.run(SseController.java:165)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:135)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1363)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:766)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:719)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:709)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1205)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 18 more
[http-nio-8080-exec-7] INFO demo.plantodo.controller.SseController - Emitter Completion
[loginThread2782569650] INFO demo.plantodo.logger.SseTrace - [Adjusting...]
Exception in thread "loginThread2782569650" java.lang.IllegalStateException: ResponseBodyEmitter has already completed
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:196)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:91)
	at demo.plantodo.controller.SseController$SendAlarmRunnable.run(SseController.java:165)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
old connection이 삭제되기 전에 new connection이 established되기 때문에 이런 문제가 발생하는 것 같다.
일단 ResponseBodyEmitter가 completed되면 재연결 시도를 포함해서 서버 측에서 어떠한 조작도 불가능하다.
이 때문에 클라이언트에게 오류가 발생했음을 알리고, 어떤 action을 취하도록 유도해야 한다.

#### 2. IOException 이후 내가 설정한 completion 로그만 찍히고 정상적으로 connection이 다시 open된 경우
이 경우 서버로부터 받아와야 하는 데이터가 있다면 받아오는 것도 좋은 practice일 수 있다.
하지만 내 경우 딱히 서버로부터 받아와야 하는 데이터가 없어서 (어차피 sleep도 서버 단에서 걸기 때문에) 클라이언트에서 뭘 할 필요는 없어 보인다.
```
org.apache.catalina.connector.ClientAbortException: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:199)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:91)
	at demo.plantodo.controller.SseController$SendAlarmRunnable.run(SseController.java:175)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:135)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1363)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:766)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:719)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:709)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1205)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 18 more
[http-nio-8080-exec-9] INFO demo.plantodo.controller.SseController - Emitter Completion
[loginThread2969857033] INFO demo.plantodo.logger.SseTrace - [Adjusting...]
```

**Comment by yeonleaf** [comment]
따라서 내가 해야 하는 것은 두 가지다.
- connection이 완벽하게 lost되었고 클라이언트에서도 다시 reconnection을 하지 않는 경우 -> 클라이언트에게 메세지를 보내서 새로고침을 유도 (새로고침을 하면 새로운 쓰레드, 새로운 eventSource 객체가 생겨나며 연결이 시작됨)
- reconnection 이후에도 valid한 전송이 이루어지도록 보장하기
